# Generated by Django 5.1.3 on 2024-12-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_venda_valor_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendedor",
            old_name="matricula",
            new_name="registro",
        ),
    ]
